import dynamic from 'next/dynamic';
import { FC } from 'react';
import { nord } from 'react-syntax-highlighter/dist/cjs/styles/hljs';

const SyntaxHighlighter = dynamic(
  async () =>
    import(
      /* webpackChunkName: "react-syntax-highlighter" */
      'react-syntax-highlighter/dist/cjs/default-highlight'
    ),
  { ssr: false }
);

export type HighlighterProps = {
  language:
    | '1c'
    | 'abnf'
    | 'accesslog'
    | 'actionscript'
    | 'ada'
    | 'angelscript'
    | 'apache'
    | 'applescript'
    | 'arcade'
    | 'arduino'
    | 'armasm'
    | 'asciidoc'
    | 'aspectj'
    | 'autohotkey'
    | 'autoit'
    | 'avrasm'
    | 'awk'
    | 'axapta'
    | 'bash'
    | 'basic'
    | 'bnf'
    | 'brainfuck'
    | 'c-like'
    | 'c'
    | 'cal'
    | 'capnproto'
    | 'ceylon'
    | 'clean'
    | 'clojure-repl'
    | 'clojure'
    | 'cmake'
    | 'coffeescript'
    | 'coq'
    | 'cos'
    | 'cpp'
    | 'crmsh'
    | 'crystal'
    | 'cs'
    | 'csharp'
    | 'csp'
    | 'css'
    | 'd'
    | 'dart'
    | 'delphi'
    | 'diff'
    | 'django'
    | 'dns'
    | 'dockerfile'
    | 'dos'
    | 'dsconfig'
    | 'dts'
    | 'dust'
    | 'ebnf'
    | 'elixir'
    | 'elm'
    | 'erb'
    | 'erlang-repl'
    | 'erlang'
    | 'excel'
    | 'fix'
    | 'flix'
    | 'fortran'
    | 'fsharp'
    | 'gams'
    | 'gauss'
    | 'gcode'
    | 'gherkin'
    | 'glsl'
    | 'gml'
    | 'go'
    | 'golo'
    | 'gradle'
    | 'groovy'
    | 'haml'
    | 'handlebars'
    | 'haskell'
    | 'haxe'
    | 'hsp'
    | 'htmlbars'
    | 'http'
    | 'hy'
    | 'index'
    | 'inform7'
    | 'ini'
    | 'irpf90'
    | 'isbl'
    | 'java'
    | 'javascript'
    | 'jboss-cli'
    | 'json'
    | 'julia-repl'
    | 'julia'
    | 'kotlin'
    | 'lasso'
    | 'latex'
    | 'ldif'
    | 'leaf'
    | 'less'
    | 'lisp'
    | 'livecodeserver'
    | 'livescript'
    | 'llvm'
    | 'lsl'
    | 'lua'
    | 'makefile'
    | 'markdown'
    | 'mathematica'
    | 'matlab'
    | 'maxima'
    | 'mel'
    | 'mercury'
    | 'mipsasm'
    | 'mizar'
    | 'mojolicious'
    | 'monkey'
    | 'moonscript'
    | 'n1ql'
    | 'nginx'
    | 'nim'
    | 'nimrod'
    | 'nix'
    | 'node-repl'
    | 'nsis'
    | 'objectivec'
    | 'ocaml'
    | 'openscad'
    | 'oxygene'
    | 'parser3'
    | 'perl'
    | 'pf'
    | 'pgsql'
    | 'php-template'
    | 'php'
    | 'plaintext'
    | 'pony'
    | 'powershell'
    | 'processing'
    | 'profile'
    | 'prolog'
    | 'properties'
    | 'protobuf'
    | 'puppet'
    | 'purebasic'
    | 'python-repl'
    | 'python'
    | 'q'
    | 'qml'
    | 'r'
    | 'reasonml'
    | 'rib'
    | 'roboconf'
    | 'routeros'
    | 'rsl'
    | 'ruby'
    | 'ruleslanguage'
    | 'rust'
    | 'sas'
    | 'scala'
    | 'scheme'
    | 'scilab'
    | 'scss'
    | 'shell'
    | 'smali'
    | 'smalltalk'
    | 'sml'
    | 'sqf'
    | 'sql'
    | 'sql_more'
    | 'stan'
    | 'stata'
    | 'step21'
    | 'stylus'
    | 'subunit'
    | 'supported-languages'
    | 'swift'
    | 'taggerscript'
    | 'tap'
    | 'tcl'
    | 'tex'
    | 'thrift'
    | 'tp'
    | 'twig'
    | 'typescript'
    | 'vala'
    | 'vbnet'
    | 'vbscript-html'
    | 'vbscript'
    | 'verilog'
    | 'vhdl'
    | 'vim'
    | 'x86asm'
    | 'xl'
    | 'xml'
    | 'xquery'
    | 'yaml'
    | 'zephir';
  children: string;
};

export const Highlighter: FC<HighlighterProps> = ({ language, children }) => (
  <SyntaxHighlighter
    language={language}
    style={nord}
    customStyle={{
      background: 'transparent',
      padding: 0,
      fontSize: 14,
    }}
  >
    {children}
  </SyntaxHighlighter>
);
